---
title: "Kari Char Big Reed"
author: "Sander Elliott - Kari Minisale"
date: "2026-01-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Packages

```{r}
library(lubridate)
library(tidyverse)
library(ggplot2)
```



# Kari's Script

```{r}
# note - the top temp logger only took one point of data on the first day
#        so I didn't include it
getwd() ## Make sure working directory all good SE

hobo_2 <- read.csv("10040750(2nd_down) - 10040750(2nd_down).csv")
hobo_3 <- read.csv("10040752_0(3rd_down) - 10040752_0(3rd_down).csv")
hobo_4 <- read.csv("10040751(4th_down) - 10040751(4th_down).csv")
hobo_5 <- read.csv("10040749(5th_down) - 10040749(5th_down).csv")
hobo_6 <- read.csv("10040748(Bottom) - 10040748(Bottom).csv")

# Library Load ----
#library(tidyverse)

# Data tidying ----
# . Adding column for hobo logger number and depth ----
hobo_2$depth <- 3
hobo_3$depth <- 5
hobo_4$depth <- 7
hobo_5$depth <- 9
hobo_6$depth <- 11

# . Adding column for hobo logger number ----
hobo_2$hobo_num <- 2
hobo_3$hobo_num <- 3
hobo_4$hobo_num <- 4
hobo_5$hobo_num <- 5
hobo_6$hobo_num <- 6

# . Smooshing everything together ----
hobo_list <- list(hobo_2, hobo_3, hobo_4, hobo_5, hobo_6)
br <- bind_rows(hobo_list)

# . Just checking ----
head(br)
unique(br$depth)
unique(br$hobo_num)
```
# Look at some stuff

## Detection by month
```{r}
class(br$Date_Time)

monthbr <- br %>% 
  mutate(Date_Time = mdy_hm(Date_Time),
         month = month(Date_Time),
         year = year(Date_Time))

start <- min(monthbr$Date_Time)
end <- max(monthbr$Date_Time) 

ggplot(monthbr, aes(x = factor(month), y = Temp_C)) +
  geom_jitter(aes(color = factor(year)), shape = 21, fill = NA, na.rm = TRUE) +
  geom_boxplot(color = "grey", fill = NA, outlier.shape = NA,
               na.rm = TRUE) +
   labs(
    title = "HOBO Temperature Readings by Month",
    subtitle = paste("Big Reed Pond, ME from", paste(start, end, sep = " to ")),
    x = "Month",
    y = "Temperature",
    color = "Year"
  ) +
  facet_wrap(factor(hobo_num)) +
  theme_classic()
 
```

HOBOs 3-6 have interesting temperature distributions for June


## Make a plot ot look at june by year

```{r}
monthbr6 <- br %>% 
  mutate(Date_Time = mdy_hm(Date_Time),
         month = month(Date_Time),
         year = year(Date_Time)) %>% 
  filter(month == 6)


ggplot(monthbr6, aes(x = factor(year), y = Temp_C)) +
  geom_jitter(aes(color = factor(year)), shape = 21, fill = NA, na.rm = TRUE) +
  geom_boxplot(color = "black", fill = NA, outlier.shape = NA,
               na.rm = TRUE) +
   labs(
    title = "HOBO Temperature Readings in June By Year",
    subtitle = paste("Big Reed Pond, ME from", paste(start, end, sep = " to ")),
    y = "Temperature",
    color = "Year"
  ) +
  facet_wrap(~ hobo_num) +
  theme_classic()
```























